########################################################################
# Copyright (c) 1988-2017 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 8/31/2017
#
# generic Gcc Makefile for framework Executable framework
########################################################################

#
# Executable target
#
framework_exe_EXETARGET = framework

########################################################################

#
# user c++ flags
#
framework_exe_USRCXXFLAGS += \
${framework_USRCXXFLAGS} \

#
# user defines
#
framework_exe_USRDEFINES = \
${framework_USRDEFINES} \

#
# user includes
#
framework_exe_USRINCLUDES = \
${framework_USRINCLUDES} \

#
# user libdirs
#
framework_exe_USRLIBDIRS = \
${framework_USRLIBDIRS} \

########################################################################

#
# Executable C++ .cpp sources
#
framework_exe_EXE_CPP_SOURCES += \
${FRAMEWORK_SRC}/xos/console/Main_main.cpp \

########################################################################

#
# Executable libraries
#
framework_exe_LIBS += \
${framework_LIBS}



